backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "setttings"
    label: "Inställningar"
    delete: false
    editor:
      preview: false
    files:
      - name: "general-settings"
        label: "Sidinställningar"
        file: "src/data/settings.json"
        description: "General Site Settings"
        fields:
          - {label: "Rubrik", name: "title", widget: "string"}

  - name: "artiklar"
    label: "Artiklar"
    label_singular: "Artikel"
    folder: "src/pages/artiklar"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nyckel", name: "templateKey", widget: "hidden", default: "single-article"}
      - {label: "Rubrik", name: "title", widget: "string"}
      - {label: "Publiceringsdatum", name: "date", widget: "datetime"}
      - {label: "Beskrivning", name: "description", widget: "text"}
      - {label: "Utvald bild", name: "featuredimage", widget: image}
      - {label: "Innehåll", name: "body", widget: "markdown"}
      - {label: "Kategorier", name: "categories", widget: "list"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}

  - name: "sidor"
    label: "Sidor"
    label_singular: "Sida"
    folder: "src/pages/sidor"
    create: true
    extension: md
    slug: '{{slug}}'
    fields:
      - {label: "Nyckel", name: "templateKey", widget: "hidden", default: "single-page"}
      - {label: "Rubrik", name: "title", widget: "string"}
      - label: "Home Section"
        name: "sections"
        widget: "list"
        types:
          - label: "Carousel"
            name: "carousel"
            widget: object
            fields:
              - {label: Header, name: header, widget: string, default: "Image Gallery"}
              - {label: Template, name: template, widget: string, default: "carousel.html"}
              - label: Images
                name: images
                widget: list
                field: {label: Image, name: image, widget: image}
          - label: "Spotlight"
            name: "spotlight"
            widget: object
            fields:
              - {label: Header, name: header, widget: string, default: "Spotlight"}
              - {label: Template, name: template, widget: string, default: "spotlight.html"}
              - {label: Text, name: text, widget: text, default: "Hello World"}