backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "setttings"
    label: "Inställningar"
    delete: false
    editor:
      preview: false
    files:
      - name: "general-settings"
        label: "Sidinställningar"
        file: "src/data/settings.json"
        description: "General Site Settings"
        fields:
          - {label: "Rubrik", name: "title", widget: "string"}

  - name: "artiklar"
    label: "Artiklar"
    label_singular: "Artikel"
    folder: "src/pages/artiklar"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nyckel", name: "templateKey", widget: "hidden", default: "single-article"}
      - {label: "Rubrik", name: "title", widget: "string"}
      - {label: "Publiceringsdatum", name: "date", widget: "datetime"}
      - {label: "Beskrivning", name: "description", widget: "text"}
      - {label: "Utvald bild", name: "featuredimage", widget: image}
      - {label: "Innehåll", name: "body", widget: "markdown"}
      - {label: "Kategorier", name: "categories", widget: "list"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}

  - name: "pages"
    label: "Sidor"
    label_singular: "Sida"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
      - label: "Modular Content Chunks"
        label_singular: "Modular Content Chunk"
        name: "chunk"
        widget: "list"
        types:
          - {label: "Text", name: "text", widget: "text"}
          - {label: "String", name: "string", widget: "string"}
          - {label: "Boolean", name: "boolean", widget: "boolean"}
          - {label: "Number", name: "number", widget: "number"}
          - {label: "Markdown", name: "markdown", widget: "markdown"}
          - {label: "Datetime", name: "datetime", widget: "datetime"}
          - {label: "Date", name: "date", widget: "date"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "File", name: "file", widget: "file"}
          - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
          - {label: "Select (Object)", name: "select_object", widget: "select", options: [{ label: "Chicago", value: "ORD" },{ label: "Paris", value: "CDG" },{ label: "Tokyo", value: "HND" }]}
          - {label: "Related Post", name: "relation", widget: "relationKitchenSinkPost", collection: "posts", searchFields: ["title", "body"], valueField: "title"}
          - label: "Profile"
            name: "profile"
            widget: "object"
            fields:
              - {label: "Public", name: "public", widget: "boolean", default: true}
              - {label: "Name", name: "name", widget: "string"}
              - label: "Birthdate"
                name: "birthdate"
                widget: "date"
          - label: "List"
            name: "list"
            widget: "list"
            fields:
              - {label: "String", name: "string", widget: "string"}
              - {label: "Boolean", name: "boolean", widget: "boolean"}
              - {label: "Text", name: "text", widget: "text"}
      - label: "List"
        name: "list"
        widget: "list"
        fields:
          - {label: "String", name: "string", widget: "string"}
          - {label: "Boolean", name: "boolean", widget: "boolean"}
          - {label: "Text", name: "text", widget: "text"}
          - {label: "Number", name: "number", widget: "number"}
          - {label: "Markdown", name: "markdown", widget: "markdown"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "File", name: "file", widget: "file"}
          - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
      - label: "Related Post"
        name: "post"
        widget: "relationKitchenSinkPost"
        collection: "posts"
        searchFields: ["title", "body"]
        valueField: "title"
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Boolean", name: "boolean", widget: "boolean", default: true}
      - {label: "Text", name: "text", widget: "text"}
      - {label: "Number", name: "number", widget: "number"}
      - {label: "Markdown", name: "markdown", widget: "markdown"}
      - {label: "Datetime", name: "datetime", widget: "datetime"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "File", name: "file", widget: "file"}
      - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
      - {label: "Hidden", name: "hidden", widget: "hidden", default: "hidden"}
      - label: "Object"
        name: "object"
        widget: "object"
        fields:
          - label: "Related Post"
            name: "post"
            widget: "relationKitchenSinkPost"
            collection: "posts"
            searchFields: ["title", "body"]
            valueField: "title"
          - {label: "String", name: "string", widget: "string"}
          - {label: "Boolean", name: "boolean", widget: "boolean", default: false}
          - {label: "Text", name: "text", widget: "text"}
          - {label: "Number", name: "number", widget: "number"}
          - {label: "Markdown", name: "markdown", widget: "markdown"}
          - {label: "Datetime", name: "datetime", widget: "datetime"}
          - {label: "Date", name: "date", widget: "date"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "File", name: "file", widget: "file"}
          - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
        meta:
          - {label: "SEO Description", name: "description", widget: "text"}