backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Inställningar"
    name: "setttings"
    delete: false
    editor:
      preview: false
    files:
      - name: "general-settings"
        label: "Sidinställningar"
        file: "src/data/settings.json"
        description: "General Site Settings"
        fields:
          - {label: "Rubrik", name: "title", widget: "string"}

  - label: "Artiklar"
    label_singular: "Artikel"
    name: "artiklar"
    folder: "src/pages/artiklar"
    create: true
    slug: "{{slug}}"
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
    fields:
      - {label: "Nyckel", name: "templateKey", widget: "hidden", default: "single-article"}
      - {label: "Rubrik", name: "title", widget: "string"}
      - {label: "Publiceringsdatum", name: "date", widget: "datetime"}
      - {label: "Beskrivning", name: "description", widget: "text"}
      - {label: "Utvald bild", name: "featuredimage", widget: image}
      - {label: "Innehåll", name: "body", widget: "markdown"}
      - {label: "Kategorier", name: "categories", widget: "list"}

  - label: "Sidor"
    label_singular: "Sida"
    name: "sidor"
    folder: "src/pages/sidor"
    create: true
    slug: '{{slug}}'
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
    fields:
      - {label: "Nyckel", name: "templateKey", widget: "hidden", default: "single-page"}
      - {label: "Rubrik", name: "title", widget: "string"}
      - label: "Sektioner"
        label_singular: "Sektion"
        name: "sections"
        widget: "list"
        types:
          - label: "Text"
            name: "text"
            widget: object
            fields:
              - {label: Rubrik, name: title, widget: string}
          - label: "Nummer"
            name: "number"
            widget: object
            fields:
              - {label: Nummer, name: number, widget: number}
          - label: "Bild"
            name: "image"
            widget: object
            fields:
              - label: Bild
                name: image
                widget: image